// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke_index from "./routes/api/joke/index.ts";
import * as $api_todos_id_ from "./routes/api/todos/[id].ts";
import * as $api_todos_index from "./routes/api/todos/index.ts";
import * as $api_todos_repository from "./routes/api/todos/repository.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $FloatingNewTodo from "./islands/FloatingNewTodo.tsx";
import * as $Todo from "./islands/Todo.tsx";
import * as $TodoList from "./islands/TodoList.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke/index.ts": $api_joke_index,
    "./routes/api/todos/[id].ts": $api_todos_id_,
    "./routes/api/todos/index.ts": $api_todos_index,
    "./routes/api/todos/repository.ts": $api_todos_repository,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/FloatingNewTodo.tsx": $FloatingNewTodo,
    "./islands/Todo.tsx": $Todo,
    "./islands/TodoList.tsx": $TodoList,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
